"""Phase 1 — Data Analysis & Exploration for MovieLens (100K-scale).

Writes figures to reports/figures/ and a write-up to reports/phase1_eda.md.
Run from movielens-100k/: ../.venv/bin/python src/eda.py
"""
from __future__ import annotations
import textwrap, datetime as dt
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid")
FIG = Path("reports/figures"); FIG.mkdir(parents=True, exist_ok=True)
OUT = Path("reports/phase1_eda.md")

md: list[str] = []
def h(s): md.append(f"\n## {s}\n"); print(f"\n=== {s} ===")
def p(s=""): md.append(str(s)); print(s)
def savefig(name):
    plt.tight_layout(); plt.savefig(FIG / name, dpi=110, bbox_inches="tight"); plt.close()
    md.append(f"\n![{name}](figures/{name})\n")

r = pd.read_csv("data/ratings.csv")
m = pd.read_csv("data/movies.csv")
r = r.merge(m, on="movieId", how="left")
r["year"] = pd.to_datetime(r["timestamp"], unit="s").dt.year

md.append("# Phase 1 — Data Analysis & Exploration\n")
md.append("MovieLens (100K-scale, CSV distribution: ratings + movies + tags). Generated by `src/eda.py`.\n")

# ---------------- 1a overview
h("1a. Data overview")
nu, ni, nr = r.userId.nunique(), r.movieId.nunique(), len(r)
p(f"- ratings: {nr:,} | users: {nu:,} | movies: {ni:,}")
p(f"- rating scale: {sorted(r.rating.unique())} (half-star)")
p(f"- user–item matrix sparsity: **{100*nr/(nu*ni):.3f}%** filled (extremely sparse).")
p(f"- time span: {r.year.min()}–{r.year.max()} | genres: {len(set(g for gg in m.genres for g in gg.split('|')))}")

# ---------------- 1b rating distribution
h("1b. Rating distribution")
plt.figure(figsize=(6.5, 4))
vc = r.rating.value_counts().sort_index()
sns.barplot(x=vc.index.astype(str), y=vc.values, palette="viridis")
plt.title(f"Rating distribution (mean={r.rating.mean():.2f})"); plt.xlabel("rating"); plt.ylabel("count")
savefig("rating_distribution.png")
p(f"- global mean rating **{r.rating.mean():.2f}**; ratings skew positive (4.0 is the mode). "
  "A global-mean predictor already sets the RMSE bar.")

# ---------------- 1c long-tail activity
h("1c. Long-tail activity (users & movies)")
rpu = r.groupby("userId").size(); rpm = r.groupby("movieId").size()
p(f"- ratings/user: min {rpu.min()}, median {int(rpu.median())}, max {rpu.max()}")
p(f"- ratings/movie: min {rpm.min()}, median {int(rpm.median())}, max {rpm.max()} "
  f"— **{(rpm<=5).mean()*100:.0f}% of movies have ≤5 ratings** (cold-start / long tail).")
plt.figure(figsize=(12, 3.8))
plt.subplot(1, 2, 1)
sns.histplot(rpu, bins=50, color="#4C72B0"); plt.yscale("log")
plt.title("Ratings per user"); plt.xlabel("# ratings"); plt.ylabel("users (log)")
plt.subplot(1, 2, 2)
sns.histplot(rpm, bins=60, color="#C44E52"); plt.yscale("log")
plt.title("Ratings per movie"); plt.xlabel("# ratings"); plt.ylabel("movies (log)")
plt.suptitle("Heavy long-tail: few heavy raters and few popular movies dominate", y=1.03)
savefig("longtail_activity.png")

# ---------------- 1d popularity bias
h("1d. Popularity vs. average rating")
stats = r.groupby("movieId").agg(n=("rating", "size"), avg=("rating", "mean"))
plt.figure(figsize=(6.5, 4.2))
plt.scatter(stats.n, stats.avg, s=6, alpha=.25, color="#55A868")
plt.xscale("log"); plt.xlabel("# ratings (log)"); plt.ylabel("average rating")
plt.title("Popularity vs average rating")
savefig("popularity_vs_rating.png")
p("- Sparsely-rated movies show extreme average ratings (1 rater → 0.5 or 5.0); popular movies regress "
  "toward ~3.5–4.0. Motivates a **bias/shrinkage baseline** and a minimum-support filter for CF.")

# ---------------- 1e genres
h("1e. Genre analysis")
exp = r.assign(genre=r.genres.str.split("|")).explode("genre")
exp = exp[exp.genre != "(no genres listed)"]
gpop = exp.genre.value_counts()
gavg = exp.groupby("genre").rating.mean().reindex(gpop.index)
fig, ax = plt.subplots(1, 2, figsize=(13, 4.6))
sns.barplot(x=gpop.values, y=gpop.index, palette="mako", ax=ax[0])
ax[0].set_title("Rating volume by genre"); ax[0].set_xlabel("# ratings")
sns.barplot(x=gavg.sort_values().values, y=gavg.sort_values().index, palette="rocket", ax=ax[1])
ax[1].axvline(r.rating.mean(), color="k", ls="--", lw=1)
ax[1].set_title("Average rating by genre (dashed = global mean)"); ax[1].set_xlabel("avg rating")
ax[1].set_xlim(3.0, 4.1)
savefig("genre_analysis.png")
p(f"- Most-rated genres: {', '.join(gpop.head(5).index)}. "
  f"Highest-rated tend to be Film-Noir/War/Documentary; lowest Horror/Comedy.")

# ---------------- 1f temporal
h("1f. Temporal trends")
plt.figure(figsize=(11, 3.6))
plt.subplot(1, 2, 1)
r.groupby("year").size().plot(marker="o", color="#4C72B0")
plt.title("Ratings per year"); plt.ylabel("# ratings"); plt.xlabel("")
plt.subplot(1, 2, 2)
r.groupby("year").rating.mean().plot(marker="o", color="#C44E52")
plt.title("Average rating per year"); plt.ylabel("avg rating"); plt.xlabel("")
savefig("temporal_trends.png")

# ---------------- 1g takeaways
h("1g. Takeaways → modeling")
p(textwrap.dedent(f"""\
- The matrix is **{100*nr/(nu*ni):.2f}% dense** → collaborative filtering must handle sparsity and cold-start.
- Positive rating skew (mean {r.rating.mean():.2f}) → subtract global/user/item biases before modeling.
- Long tail: {(rpm<=5).mean()*100:.0f}% of movies have ≤5 ratings → apply a minimum-support filter for kNN CF
  and rely on latent factors (matrix factorization) to generalize.
- Two evaluation tasks: **rating prediction** (RMSE/MAE) and **top-N recommendation** (Precision@K,
  Recall@K, NDCG@K) with a per-user hold-out.
- Genres enable a content baseline and a hybrid fallback for cold-start items.
"""))

OUT.write_text("\n".join(md))
print(f"\nWrote {OUT} and figures to {FIG}")
